### ISSUE TITLE
Alterações nos conteúdos

### ISSUE THREAD

**Issue by apag-guimaraes** [fagno/moodle-tutorial#1]
Boa tarde Fagno, segue algumas sugestões de alterações nas apresentações dos tópicos e conteúdos do material. 
ATT.

**Comment by fagno** [comment]
Olá Ana, poderia fazer uma breve descrição das sugestões e implementações que deseja?

**Comment by apag-guimaraes** [comment]
Bom dia Fagno, segue as descrições:

1. Alterações na página inicial relacionada com a estrutura de apresentação dos tópicos centrais;
2. Alterações na página que apresenta o tópico Moodle, menos textos nas explanações visando uma redução na sobrecarga visual;
3. A mesma ideia do item 2 nos tópicos relacionados com o Classroom e Google Meet.

ATT.
